layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Automatic lyrics transcription using dilated convolutional neural networks
    image_url: posts/transformer_hybridASR/hybridASR.png
    web_url: https://arxiv.org/abs/2007.06486
    description: Conference paper published in the Proceedings of IJCNN2020. Novel neural network architecture. State-of-the-art results in automatic lyrics transcription from monophonic recordings.
    
  - name: MIREX 2019 - Audio-to-Lyrics Alignment Challenge
    image_url: figures/mirex2019.png
